### ISSUE TITLE
авторестарт службы при эксепшне апишки

### ISSUE THREAD

**Issue by kotenki** [kotenki/watchdog#17]
```
2022-09-16 15:40:52,422 (__init__.py:880 MainThread) ERROR - TeleBot: "Exception traceback:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 423, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 330, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/telebot/__init__.py", line 874, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "/usr/local/lib/python3.8/dist-packages/telebot/__init__.py", line 946, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "/usr/local/lib/python3.8/dist-packages/telebot/__init__.py", line 1021, in __threaded_polling
    raise e
  File "/usr/local/lib/python3.8/dist-packages/telebot/__init__.py", line 976, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/usr/local/lib/python3.8/dist-packages/telebot/util.py", line 116, in raise_exceptions
    raise self.exception_info
  File "/usr/local/lib/python3.8/dist-packages/telebot/util.py", line 98, in run
    task(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/telebot/__init__.py", line 601, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "/usr/local/lib/python3.8/dist-packages/telebot/__init__.py", line 575, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "/usr/local/lib/python3.8/dist-packages/telebot/apihelper.py", line 333, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/usr/local/lib/python3.8/dist-packages/telebot/apihelper.py", line 155, in _make_request
    result = _get_req_session().request(
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
"
Traceback (most recent call last):
  File "watchdog.py", line 47, in <module>
    set_prices(get_prices())
  File "watchdog.py", line 32, in get_prices
    return cg.get_price(ids=tokens_string.lower(), vs_currencies="usd")
  File "/usr/local/lib/python3.8/dist-packages/pycoingecko/utils.py", line 12, in input_args
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pycoingecko/api.py", line 78, in get_price
    return self.__request(api_url)
  File "/usr/local/lib/python3.8/dist-packages/pycoingecko/api.py", line 29, in __request
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 530 Server Error:  for url: https://api.coingecko.com/api/v3/simple/price?ids=bitcoin,ethereum,tether,usd-coin,binancecoin,binance-usd,ripple,cardano,solana,polkadot,dogecoin,shiba-inu,staked-ether,matic-network,dai,avalanche-2,tron,ethereum-classic,wrapped-bitcoin,uniswap,leo-token,cosmos,litecoin,okb,chainlink,near,ftx-token,terra-luna,crypto-com-chain,monero,stellar,bitcoin-cash,algorand,flow,vechain,internet-computer,filecoin,eos,apecoin,frax,tezos,decentraland,chain-2,hedera-hashgraph,the-sandbox,quant-network,axie-infinity,aave,elrond-erd-2,lido-dao,theta-token,true-usd,chiliz,bitcoin-cash-sv,compound-usd-coin,paxos-standard,kucoin-shares,bittorrent,ecash,zcash,the-graph,huobi-btc,iota,evmos,usdd,huobi-token,havven,maker,klay-token,neo,fantom,bitdao,cdai,neutrino,helium,osmosis,compound-ether,gatechain-token,defichain,radix,pancakeswap-token,thorchain,celsius-degree-token,arweave,pax-gold,enjincoin,zilliqa,dash,basic-attention-token,rocket-pool,ravencoin,nexo,blockstack,frax-share,kusama,curve-dao-token,waves,tokenize-xchange,bitcoin-gold,loopring,amp-token,decred,trust-wallet-token,kava,gnosis,gmx,tether-gold,stepn,ethereum-name-service,tenset,nem,terrausd,celo,mina-protocol,ecomi,gala,1inch,holotoken,convex-finance,nxm,gemini-dollar,synapse-2,compound-governance-token,qtum,xdce-crowd-sale,theta-fuel,juno-network,zelcash,maiar-dex,terra-luna-2,oasis-network,serum,compound-usdt,oec-token,kadena,iostoken,ankr,yearn-finance,convex-crv,olympus,ergo,iotex,golem,safemoon,livepeer,optimism,balancer,omisego,reserve-rights-token,0x,msol,harmony,sushi,polymath,ethos,just,audius,link,escoin-token,icon,songbird,ontology,zencash,magic-internet-money,wax,dao-maker,siacoin,secret,hive,tether-eurt,safemoon-2,nucypher,merit-circle,immutable-x,energy-web-token,baby-doge-coin,constellation-labs,dydx,skale,swipe,kyber-network-crystal,moonbeam,woo-network,uma,coinmetro,coin-of-the-champions,chia,liquity-usd,alchemix-usd,swissborg,mxc,playdapp,digibyte,casper-network,pocket-network,smooth-love-potion,apenft,render-token,dogelon-mars,lisk,kintsugi,interlay,forta,vega-coin,the-open-network,acala-dollar,agoric,zebec-protocol,nervos-network,sweatcoin&vs_currencies=usd

```

**Comment by kotenki** [comment]
d2e12ac
